# Generated by Django 2.2 on 2019-04-15 11:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190415_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='task1',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task1',
            name='due_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task1',
            name='status',
            field=models.CharField(default="ok", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task1',
            name='task_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TaskList1'),
            preserve_default=False,
        ),
    ]
