# Generated by Django 2.2 on 2019-04-15 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190415_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task1',
            name='status',
        ),
    ]
