# Generated by Django 2.2 on 2019-04-15 20:38

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('api', '0004_remove_task1_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task1',
            new_name='Task',
        ),
        migrations.RenameModel(
            old_name='TaskList1',
            new_name='TaskList',
        ),
    ]
